#ifndef CONFIG_H
#define CONFIG_H

#define DEFAULT_WAN_IF "wan"
#define DEFAULT_IFB_IF "ifb0"
#define DEFAULT_LINE_RATE_MBIT 300
#define DEFAULT_PROTECT_RATE_MBIT 80
#define DEFAULT_TRIGGER_DELAY_MS 2000
#define DEFAULT_HOLD_TIME_MS 5000
#define DEFAULT_POLL_INTERVAL_MS 500
#define DEFAULT_LOG_INTERVAL_MS 2000
#define DEFAULT_RECOVER_STEP_MBIT 20

#define SMALL_PACKET_BYTES 300
#define LARGE_PACKET_BYTES 1000

#define DEFAULT_REALTIME_MAX_KBPS 300
#define DEFAULT_BULK_MIN_KBPS 2048
#define DEFAULT_REALTIME_MIN_PPS 10
#define DEFAULT_REALTIME_MAX_PPS 120
#define DEFAULT_REALTIME_SCORE_THRESHOLD 6
#define DEFAULT_BULK_SCORE_THRESHOLD 6

#endif
